import 'package:flutter/material.dart';

Color keyboardKey = Colors.black45;
Color keyboardLetter = Colors.white;
Color questionCard = Colors.black45;
Color descriptionCard = Colors.black54;
Color descriptionText = Colors.white;
Color boxesCard = Colors.black54;
Color boxBorder = Colors.cyan;
Color boxText = Colors.white;
Color boxBackground = Colors.black45;
Color boxAfterHintBackground = Colors.black87;
Color boxCorrect = Colors.cyan;
Color boxCorrectAccent = Colors.cyanAccent;
Color boxError = Colors.redAccent;
Color hintBorder = Colors.cyan;
Color hintText = Colors.cyan;
Color header = Colors.black54;
Color arrowColor = Colors.white;
Color roundNumber = Colors.white;
Color snackbarBackground = Colors.black54;
Color snackbarText = Colors.white;
Color dialogBackground = Colors.black54;
Color dialogText = Colors.white;
